### ISSUE TITLE
Needed to change the order of the 'create' command's parameters

### ISSUE THREAD

**Issue by gdfelt** [Louisvh/TugShuttle#5] opened 2016-07-11 17:26 UTC
Just a note that I needed to put the droplet name toward the beginning of the command instead of at the end in order to run it:

`tugboat create tugshuttle-to-$region -r $region -s 512mb -i debian-8-x64 -k $keyID 
`

Must have been a recent change to the way the tugboat command works.

**Comment by Louisvh** [comment] 2016-07-13 23:21
Can't reproduce, but changing this shouldn't break anything. Fixed in the latest commit.

**Closed as completed by Louisvh** 2016-07-13 23:21 UTC
